name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node 20 + pnpm installieren
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm install -g pnpm@8   # stabile Version
      
      # Dependencies installieren via pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm -r build

      - name: Publish via Changesets
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish
          setupGitUser: true
          createGithubReleases: true
          commitMode: git-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy-cloudflare:
    runs-on: ubuntu-latest
    needs: release
    env:
      CLOUDFLARE_PROJECT_NAME: zoompinch
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install playground dependencies
        working-directory: vue/playground
        run: npm install

      - name: Build playground
        working-directory: vue/playground
        run: npm build

      - name: Deploy to Cloudflare Pages
        working-directory: vue/playground
        run: npx wrangler pages deploy dist --project-name ${{ env.CLOUDFLARE_PROJECT_NAME }} --branch main
